<?xml version="1.0" encoding="utf-8"?><Database Name="DB_CONTRATOS" Class="DB_CONTRATOSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=DB_CONTRATOS;Integrated Security=True" SettingsObjectName="GestaoContratos.Data.Properties.Settings" SettingsPropertyName="DB_CONTRATOSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CONTRATOS" Member="CONTRATOs">
    <Type Name="CONTRATO">
      <Column Name="ID_CONTRATO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PARCEIRO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_USER_RESPONSAVEL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_FINALIDADE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NUMERO_CONTRATO" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DATA_INICIO" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="DATA_FIM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="PRAZO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="VALOR_CONTRATO" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="STATUS_CONTRATO" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DATA_CADASTRO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PARCEIROS_CONTRATO" Member="PARCEIROS" Storage="_PARCEIRO" ThisKey="ID_PARCEIRO" OtherKey="ID_PARCEIRO" Type="PARCEIROS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PARCEIROS" Member="PARCEIROS">
    <Type Name="PARCEIROS">
      <Column Name="ID_PARCEIRO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INDICA_CPF_CNPJ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INDICA_CLIENTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INDICA_FORNECEDOR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CODIGO_PARCEIRO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOME_PARCEIRO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPF_CNPJ" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CELULAR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CEP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LOGRADOURO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NUMERO" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="COMPLEMENTO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BAIRRO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CIDADE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UF" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="INATIVO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DATA_CADASTRO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PARCEIROS_CONTRATO" Member="CONTRATOs" ThisKey="ID_PARCEIRO" OtherKey="ID_PARCEIRO" Type="CONTRATO" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIOS" Member="USUARIOs">
    <Type Name="USUARIO">
      <Column Name="ID_USUARIO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME_USUARIO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LOGIN" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SENHA" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DATA_CADASTRO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>