#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoContratos.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_CONTRATOS")]
	public partial class DB_CONTRATOSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCONTRATO(CONTRATO instance);
    partial void UpdateCONTRATO(CONTRATO instance);
    partial void DeleteCONTRATO(CONTRATO instance);
    partial void InsertPARCEIROS(PARCEIROS instance);
    partial void UpdatePARCEIROS(PARCEIROS instance);
    partial void DeletePARCEIROS(PARCEIROS instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    #endregion
		
		public DB_CONTRATOSDataContext() : 
				base(global::GestaoContratos.Data.Properties.Settings.Default.DB_CONTRATOSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CONTRATOSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CONTRATOSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CONTRATOSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CONTRATOSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CONTRATO> CONTRATOs
		{
			get
			{
				return this.GetTable<CONTRATO>();
			}
		}
		
		public System.Data.Linq.Table<PARCEIROS> PARCEIROS
		{
			get
			{
				return this.GetTable<PARCEIROS>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIOs
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONTRATOS")]
	public partial class CONTRATO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CONTRATO;
		
		private int _ID_PARCEIRO;
		
		private int _ID_USER_RESPONSAVEL;
		
		private int _ID_FINALIDADE;
		
		private string _NUMERO_CONTRATO;
		
		private System.DateTime _DATA_INICIO;
		
		private System.Nullable<System.DateTime> _DATA_FIM;
		
		private System.Nullable<decimal> _PRAZO;
		
		private decimal _VALOR_CONTRATO;
		
		private string _STATUS_CONTRATO;
		
		private System.Nullable<System.DateTime> _DATA_CADASTRO;
		
		private EntityRef<PARCEIROS> _PARCEIRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CONTRATOChanging(int value);
    partial void OnID_CONTRATOChanged();
    partial void OnID_PARCEIROChanging(int value);
    partial void OnID_PARCEIROChanged();
    partial void OnID_USER_RESPONSAVELChanging(int value);
    partial void OnID_USER_RESPONSAVELChanged();
    partial void OnID_FINALIDADEChanging(int value);
    partial void OnID_FINALIDADEChanged();
    partial void OnNUMERO_CONTRATOChanging(string value);
    partial void OnNUMERO_CONTRATOChanged();
    partial void OnDATA_INICIOChanging(System.DateTime value);
    partial void OnDATA_INICIOChanged();
    partial void OnDATA_FIMChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_FIMChanged();
    partial void OnPRAZOChanging(System.Nullable<decimal> value);
    partial void OnPRAZOChanged();
    partial void OnVALOR_CONTRATOChanging(decimal value);
    partial void OnVALOR_CONTRATOChanged();
    partial void OnSTATUS_CONTRATOChanging(string value);
    partial void OnSTATUS_CONTRATOChanged();
    partial void OnDATA_CADASTROChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_CADASTROChanged();
    #endregion
		
		public CONTRATO()
		{
			this._PARCEIRO = default(EntityRef<PARCEIROS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTRATO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CONTRATO
		{
			get
			{
				return this._ID_CONTRATO;
			}
			set
			{
				if ((this._ID_CONTRATO != value))
				{
					this.OnID_CONTRATOChanging(value);
					this.SendPropertyChanging();
					this._ID_CONTRATO = value;
					this.SendPropertyChanged("ID_CONTRATO");
					this.OnID_CONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PARCEIRO", DbType="Int NOT NULL")]
		public int ID_PARCEIRO
		{
			get
			{
				return this._ID_PARCEIRO;
			}
			set
			{
				if ((this._ID_PARCEIRO != value))
				{
					if (this._PARCEIRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PARCEIROChanging(value);
					this.SendPropertyChanging();
					this._ID_PARCEIRO = value;
					this.SendPropertyChanged("ID_PARCEIRO");
					this.OnID_PARCEIROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER_RESPONSAVEL", DbType="Int NOT NULL")]
		public int ID_USER_RESPONSAVEL
		{
			get
			{
				return this._ID_USER_RESPONSAVEL;
			}
			set
			{
				if ((this._ID_USER_RESPONSAVEL != value))
				{
					this.OnID_USER_RESPONSAVELChanging(value);
					this.SendPropertyChanging();
					this._ID_USER_RESPONSAVEL = value;
					this.SendPropertyChanged("ID_USER_RESPONSAVEL");
					this.OnID_USER_RESPONSAVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FINALIDADE", DbType="Int NOT NULL")]
		public int ID_FINALIDADE
		{
			get
			{
				return this._ID_FINALIDADE;
			}
			set
			{
				if ((this._ID_FINALIDADE != value))
				{
					this.OnID_FINALIDADEChanging(value);
					this.SendPropertyChanging();
					this._ID_FINALIDADE = value;
					this.SendPropertyChanged("ID_FINALIDADE");
					this.OnID_FINALIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_CONTRATO", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NUMERO_CONTRATO
		{
			get
			{
				return this._NUMERO_CONTRATO;
			}
			set
			{
				if ((this._NUMERO_CONTRATO != value))
				{
					this.OnNUMERO_CONTRATOChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_CONTRATO = value;
					this.SendPropertyChanged("NUMERO_CONTRATO");
					this.OnNUMERO_CONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_INICIO", DbType="DateTime")]
		public System.DateTime DATA_INICIO
		{
			get
			{
				return this._DATA_INICIO;
			}
			set
			{
				if ((this._DATA_INICIO != value))
				{
					this.OnDATA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._DATA_INICIO = value;
					this.SendPropertyChanged("DATA_INICIO");
					this.OnDATA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_FIM", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> DATA_FIM
		{
			get
			{
				return this._DATA_FIM;
			}
			set
			{
				if ((this._DATA_FIM != value))
				{
					this.OnDATA_FIMChanging(value);
					this.SendPropertyChanging();
					this._DATA_FIM = value;
					this.SendPropertyChanged("DATA_FIM");
					this.OnDATA_FIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRAZO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PRAZO
		{
			get
			{
				return this._PRAZO;
			}
			set
			{
				if ((this._PRAZO != value))
				{
					this.OnPRAZOChanging(value);
					this.SendPropertyChanging();
					this._PRAZO = value;
					this.SendPropertyChanged("PRAZO");
					this.OnPRAZOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_CONTRATO", DbType="Money NOT NULL")]
		public decimal VALOR_CONTRATO
		{
			get
			{
				return this._VALOR_CONTRATO;
			}
			set
			{
				if ((this._VALOR_CONTRATO != value))
				{
					this.OnVALOR_CONTRATOChanging(value);
					this.SendPropertyChanging();
					this._VALOR_CONTRATO = value;
					this.SendPropertyChanged("VALOR_CONTRATO");
					this.OnVALOR_CONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_CONTRATO", DbType="Char(10)")]
		public string STATUS_CONTRATO
		{
			get
			{
				return this._STATUS_CONTRATO;
			}
			set
			{
				if ((this._STATUS_CONTRATO != value))
				{
					this.OnSTATUS_CONTRATOChanging(value);
					this.SendPropertyChanging();
					this._STATUS_CONTRATO = value;
					this.SendPropertyChanged("STATUS_CONTRATO");
					this.OnSTATUS_CONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_CADASTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_CADASTRO
		{
			get
			{
				return this._DATA_CADASTRO;
			}
			set
			{
				if ((this._DATA_CADASTRO != value))
				{
					this.OnDATA_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DATA_CADASTRO = value;
					this.SendPropertyChanged("DATA_CADASTRO");
					this.OnDATA_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PARCEIROS_CONTRATO", Storage="_PARCEIRO", ThisKey="ID_PARCEIRO", OtherKey="ID_PARCEIRO", IsForeignKey=true)]
		public PARCEIROS PARCEIROS
		{
			get
			{
				return this._PARCEIRO.Entity;
			}
			set
			{
				PARCEIROS previousValue = this._PARCEIRO.Entity;
				if (((previousValue != value) 
							|| (this._PARCEIRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PARCEIRO.Entity = null;
						previousValue.CONTRATOs.Remove(this);
					}
					this._PARCEIRO.Entity = value;
					if ((value != null))
					{
						value.CONTRATOs.Add(this);
						this._ID_PARCEIRO = value.ID_PARCEIRO;
					}
					else
					{
						this._ID_PARCEIRO = default(int);
					}
					this.SendPropertyChanged("PARCEIROS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PARCEIROS")]
	public partial class PARCEIROS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PARCEIRO;
		
		private int _INDICA_CPF_CNPJ;
		
		private System.Nullable<int> _INDICA_CLIENTE;
		
		private System.Nullable<int> _INDICA_FORNECEDOR;
		
		private string _CODIGO_PARCEIRO;
		
		private string _NOME_PARCEIRO;
		
		private string _CPF_CNPJ;
		
		private string _EMAIL;
		
		private string _CELULAR;
		
		private string _CEP;
		
		private string _LOGRADOURO;
		
		private string _NUMERO;
		
		private string _COMPLEMENTO;
		
		private string _BAIRRO;
		
		private string _CIDADE;
		
		private string _UF;
		
		private int _INATIVO;
		
		private System.Nullable<System.DateTime> _DATA_CADASTRO;
		
		private EntitySet<CONTRATO> _CONTRATOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PARCEIROChanging(int value);
    partial void OnID_PARCEIROChanged();
    partial void OnINDICA_CPF_CNPJChanging(int value);
    partial void OnINDICA_CPF_CNPJChanged();
    partial void OnINDICA_CLIENTEChanging(System.Nullable<int> value);
    partial void OnINDICA_CLIENTEChanged();
    partial void OnINDICA_FORNECEDORChanging(System.Nullable<int> value);
    partial void OnINDICA_FORNECEDORChanged();
    partial void OnCODIGO_PARCEIROChanging(string value);
    partial void OnCODIGO_PARCEIROChanged();
    partial void OnNOME_PARCEIROChanging(string value);
    partial void OnNOME_PARCEIROChanged();
    partial void OnCPF_CNPJChanging(string value);
    partial void OnCPF_CNPJChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnLOGRADOUROChanging(string value);
    partial void OnLOGRADOUROChanged();
    partial void OnNUMEROChanging(string value);
    partial void OnNUMEROChanged();
    partial void OnCOMPLEMENTOChanging(string value);
    partial void OnCOMPLEMENTOChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    partial void OnCIDADEChanging(string value);
    partial void OnCIDADEChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnINATIVOChanging(int value);
    partial void OnINATIVOChanged();
    partial void OnDATA_CADASTROChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_CADASTROChanged();
    #endregion
		
		public PARCEIROS()
		{
			this._CONTRATOs = new EntitySet<CONTRATO>(new Action<CONTRATO>(this.attach_CONTRATOs), new Action<CONTRATO>(this.detach_CONTRATOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PARCEIRO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PARCEIRO
		{
			get
			{
				return this._ID_PARCEIRO;
			}
			set
			{
				if ((this._ID_PARCEIRO != value))
				{
					this.OnID_PARCEIROChanging(value);
					this.SendPropertyChanging();
					this._ID_PARCEIRO = value;
					this.SendPropertyChanged("ID_PARCEIRO");
					this.OnID_PARCEIROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDICA_CPF_CNPJ", DbType="Int NOT NULL")]
		public int INDICA_CPF_CNPJ
		{
			get
			{
				return this._INDICA_CPF_CNPJ;
			}
			set
			{
				if ((this._INDICA_CPF_CNPJ != value))
				{
					this.OnINDICA_CPF_CNPJChanging(value);
					this.SendPropertyChanging();
					this._INDICA_CPF_CNPJ = value;
					this.SendPropertyChanged("INDICA_CPF_CNPJ");
					this.OnINDICA_CPF_CNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDICA_CLIENTE", DbType="Int")]
		public System.Nullable<int> INDICA_CLIENTE
		{
			get
			{
				return this._INDICA_CLIENTE;
			}
			set
			{
				if ((this._INDICA_CLIENTE != value))
				{
					this.OnINDICA_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._INDICA_CLIENTE = value;
					this.SendPropertyChanged("INDICA_CLIENTE");
					this.OnINDICA_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDICA_FORNECEDOR", DbType="Int")]
		public System.Nullable<int> INDICA_FORNECEDOR
		{
			get
			{
				return this._INDICA_FORNECEDOR;
			}
			set
			{
				if ((this._INDICA_FORNECEDOR != value))
				{
					this.OnINDICA_FORNECEDORChanging(value);
					this.SendPropertyChanging();
					this._INDICA_FORNECEDOR = value;
					this.SendPropertyChanged("INDICA_FORNECEDOR");
					this.OnINDICA_FORNECEDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PARCEIRO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODIGO_PARCEIRO
		{
			get
			{
				return this._CODIGO_PARCEIRO;
			}
			set
			{
				if ((this._CODIGO_PARCEIRO != value))
				{
					this.OnCODIGO_PARCEIROChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_PARCEIRO = value;
					this.SendPropertyChanged("CODIGO_PARCEIRO");
					this.OnCODIGO_PARCEIROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_PARCEIRO", DbType="NVarChar(50)")]
		public string NOME_PARCEIRO
		{
			get
			{
				return this._NOME_PARCEIRO;
			}
			set
			{
				if ((this._NOME_PARCEIRO != value))
				{
					this.OnNOME_PARCEIROChanging(value);
					this.SendPropertyChanging();
					this._NOME_PARCEIRO = value;
					this.SendPropertyChanged("NOME_PARCEIRO");
					this.OnNOME_PARCEIROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF_CNPJ", DbType="NVarChar(14)")]
		public string CPF_CNPJ
		{
			get
			{
				return this._CPF_CNPJ;
			}
			set
			{
				if ((this._CPF_CNPJ != value))
				{
					this.OnCPF_CNPJChanging(value);
					this.SendPropertyChanging();
					this._CPF_CNPJ = value;
					this.SendPropertyChanged("CPF_CNPJ");
					this.OnCPF_CNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="NVarChar(50)")]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="NChar(10)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGRADOURO", DbType="NVarChar(50)")]
		public string LOGRADOURO
		{
			get
			{
				return this._LOGRADOURO;
			}
			set
			{
				if ((this._LOGRADOURO != value))
				{
					this.OnLOGRADOUROChanging(value);
					this.SendPropertyChanging();
					this._LOGRADOURO = value;
					this.SendPropertyChanged("LOGRADOURO");
					this.OnLOGRADOUROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO", DbType="NChar(10)")]
		public string NUMERO
		{
			get
			{
				return this._NUMERO;
			}
			set
			{
				if ((this._NUMERO != value))
				{
					this.OnNUMEROChanging(value);
					this.SendPropertyChanging();
					this._NUMERO = value;
					this.SendPropertyChanged("NUMERO");
					this.OnNUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLEMENTO", DbType="NVarChar(50)")]
		public string COMPLEMENTO
		{
			get
			{
				return this._COMPLEMENTO;
			}
			set
			{
				if ((this._COMPLEMENTO != value))
				{
					this.OnCOMPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._COMPLEMENTO = value;
					this.SendPropertyChanged("COMPLEMENTO");
					this.OnCOMPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="NVarChar(50)")]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="NVarChar(50)")]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this.OnCIDADEChanging(value);
					this.SendPropertyChanging();
					this._CIDADE = value;
					this.SendPropertyChanged("CIDADE");
					this.OnCIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="NChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INATIVO", DbType="Int NOT NULL")]
		public int INATIVO
		{
			get
			{
				return this._INATIVO;
			}
			set
			{
				if ((this._INATIVO != value))
				{
					this.OnINATIVOChanging(value);
					this.SendPropertyChanging();
					this._INATIVO = value;
					this.SendPropertyChanged("INATIVO");
					this.OnINATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_CADASTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_CADASTRO
		{
			get
			{
				return this._DATA_CADASTRO;
			}
			set
			{
				if ((this._DATA_CADASTRO != value))
				{
					this.OnDATA_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DATA_CADASTRO = value;
					this.SendPropertyChanged("DATA_CADASTRO");
					this.OnDATA_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PARCEIROS_CONTRATO", Storage="_CONTRATOs", ThisKey="ID_PARCEIRO", OtherKey="ID_PARCEIRO")]
		public EntitySet<CONTRATO> CONTRATOs
		{
			get
			{
				return this._CONTRATOs;
			}
			set
			{
				this._CONTRATOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONTRATOs(CONTRATO entity)
		{
			this.SendPropertyChanging();
			entity.PARCEIROS = this;
		}
		
		private void detach_CONTRATOs(CONTRATO entity)
		{
			this.SendPropertyChanging();
			entity.PARCEIROS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIOS")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIO;
		
		private string _NOME_USUARIO;
		
		private string _LOGIN;
		
		private string _SENHA;
		
		private string _EMAIL;
		
		private bool _INATIVO;
		
		private System.DateTime _DATA_CADASTRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnNOME_USUARIOChanging(string value);
    partial void OnNOME_USUARIOChanged();
    partial void OnLOGINChanging(string value);
    partial void OnLOGINChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnINATIVOChanging(bool value);
    partial void OnINATIVOChanged();
    partial void OnDATA_CADASTROChanging(System.DateTime value);
    partial void OnDATA_CADASTROChanged();
    #endregion
		
		public USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_USUARIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME_USUARIO
		{
			get
			{
				return this._NOME_USUARIO;
			}
			set
			{
				if ((this._NOME_USUARIO != value))
				{
					this.OnNOME_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._NOME_USUARIO = value;
					this.SendPropertyChanged("NOME_USUARIO");
					this.OnNOME_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGIN", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string LOGIN
		{
			get
			{
				return this._LOGIN;
			}
			set
			{
				if ((this._LOGIN != value))
				{
					this.OnLOGINChanging(value);
					this.SendPropertyChanging();
					this._LOGIN = value;
					this.SendPropertyChanged("LOGIN");
					this.OnLOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INATIVO", DbType="Bit NOT NULL")]
		public bool INATIVO
		{
			get
			{
				return this._INATIVO;
			}
			set
			{
				if ((this._INATIVO != value))
				{
					this.OnINATIVOChanging(value);
					this.SendPropertyChanging();
					this._INATIVO = value;
					this.SendPropertyChanged("INATIVO");
					this.OnINATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DATA_CADASTRO
		{
			get
			{
				return this._DATA_CADASTRO;
			}
			set
			{
				if ((this._DATA_CADASTRO != value))
				{
					this.OnDATA_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DATA_CADASTRO = value;
					this.SendPropertyChanged("DATA_CADASTRO");
					this.OnDATA_CADASTROChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
